### PR TITLE
Test specs

### PR DESCRIPTION
**Pull request by PeteJodo**
I may be missing some specs, the codebase changed a little bit since the last time I used it. Just let me know

### CODE REVIEW

**Comment by PeteJodo** [comment]
Oh I forgot all the specs for `closeOnEsc`, `closeOnOutsideClick`, and `style`. Whoops. Will implement over the weekend. I guess hold out on merging anything

**Comment by PeteJodo** [comment]
Also seems like my .babelrc file is messing with the build. Will fix as well

**Comment by tajo** [comment]
Thanks! Looking good so far. I'm gonna also change the build process then (removal of gulp, browserify, npm prepublish .... adding webpack).

**Comment by PeteJodo** [comment]
Yeah I'm having a hard time figuring out why the build isn't working

**Comment by PeteJodo** [comment]
Added the missing tests, just need to figure out the build issue now

**Comment by tajo** [comment]
Thanks! It's brilliant! I'm gonna merge it asap with a new build process, so don't worry about it.

**Comment by tajo** [comment]
Thanks again! It's merged. (I did some git history modifications, so I had to force push the master.)

**Pull request closed without merging**
