### PR TITLE
preserve the original onClick event handler of the openByClickOn element

### PR DESCRIPTION
**Pull request by Diablohu**

### CODE REVIEW

**Comment by tajo** [comment]
I am a bit worried that this could introduce new issues and weird behaviors. Can you just use `isOpen` approach if you need to do multiple things after `onClick`?

Anyone else?
Thank you!

**Comment by Diablohu** [comment]
Sorry for my poor English...

The reason I want the original onClick event handler of the openByClickOn element preserved is that I want to get the openByClickOn element's DOM. Though I can bind other event handler on openByClickOn element, but that is not optimal solution. And as I know, the openByClickOn element pass through *props* is cloned, so *ref* is not available.

*button3* in the original examples is the most similar for this situation, but that method make the element wrapper in a new *div* which is not my disired result.

For the very reason, is there any other solution?

**Comment by tajo** [comment]
Hey, please check the new major version (complete rewrite) of react-portal:  https://github.com/tajo/react-portal/issues/157

**It's React v16 only since its uses the new official Portal API**. There is the first beta released and I would like to get your feedback. I don't have bandwidth to maintain v3 which is very different and full of hacks. 

If you feel your PR still applies, please rebase it against the master and re-open it. Sorry for the lack of response in past! Thanks!

**Comment by Diablohu** [comment]
I will try out React 16. Thanks!

**Pull request closed without merging**
