### PR TITLE
Added functionality for portal targets + fix conflicts & CI

### PR DESCRIPTION
**Pull request by Hypnosphi**
This is a fix for #100

### CODE REVIEW

**Comment by robinfehr** [comment]
cool +1

**Comment by kevinahuber** [comment]
This is great! 👍

**Comment by princed** [comment]
@tajo Is there a chance it could be merged?

**Comment by davideickhoff** [comment]
any new plans for merging?

**Comment by princed** [comment]
In the meanwhile, feel free to use our [scoped package](https://www.npmjs.com/package/@hypnosphi/react-portal) (https://github.com/Hypnosphi/react-portal/tree/scoped). No warranties  whatsoever.

**Comment by arronhunt** [comment]
Bumping for this one

**Comment by Hypnosphi** [comment]
I've rebased our branch to fit into the new project structure

**Comment by ablamunits** [comment]
@Hypnosphi Thank you for this, I am using this off of your forked repo.
Any chance this will be merged here? Could be awesome.

**Comment by tajo** [comment]
Hey, please check the new major version (complete rewrite) of react-portal:  https://github.com/tajo/react-portal/issues/157

**It's React v16 only since its uses the new official Portal API**. There is the first beta released and I would like to get your feedback. I don't have bandwidth to maintain v3 which is very different and full of hacks. 

If you feel your PR still applies, please rebase it against the master and re-open it. Sorry for the lack of response in past! Thanks!

**Pull request closed without merging**
