### PR TITLE
Upgrade to React 0.14

### LINKED ISSUE #8: Warning: owner-based and parent-based contexts differ
There is a new warning after update to React v.0.13.3. I am not sure how to fix it (if possible).

```
Warning: owner-based and parent-based contexts differ (values: `function (props, context) {
      // This constructor is overridden by mocks. The argument is used
      // by mocks to assert on what gets mounted.

      if ("production" !== "development") {
        ("production" !== "development" ? warning(
          this instanceof Constructor,
          'Something is calling a React component directly. Use a factory or ' +
          'JSX instead. See: https://fb.me/react-legacyfactory'
        ) : null);
      }

      // Wire up auto-binding
      if (this.__reactAutoBindMap) {
        bindAutoBindMethods(this);
      }

      this.props = props;
      this.context = context;
      this.state = null;

      // ReactClasses doesn't have constructors. Instead, they use the
      // getInitialState and componentWillMount methods for initialization.

      var initialState = this.getInitialState ? this.getInitialState() : null;
      if ("production" !== "development") {
        // We allow auto-mocks to proceed as if they're returning null.
        if (typeof initialState === 'undefined' &&
            this.getInitialState._isMockFunction) {
          // This is probably bad practice. Consider warning here and
          // deprecating this convenience.
          initialState = null;
        }
      }
      ("production" !== "development" ? invariant(
        typeof initialState === 'object' && !Array.isArray(initialState),
        '%s.getInitialState(): must return an object or null',
        Constructor.displayName || 'ReactCompositeComponent'
      ) : invariant(typeof initialState === 'object' && !Array.isArray(initialState)));

      this.state = initialState;
    }` vs `undefined`) for key (router) while mounting Lightbox (see: http://fb.me/react-context-by-parent)
```

### PR DESCRIPTION
**Pull request by nicolashery**
Fixes #8, #17, #18

### CODE REVIEW

**Comment by tajo** [comment]
Thanks! I'll merge it with the stable React 0.14.0.

**Comment by nicolashery** [comment]
No problem!

Yes, probably better to wait for stable React 0.14.0. I'm having trouble upgrading my project because a lot of the 3rd-party React components I'm using are still on 0.13, so have to wait a bit before going to 0.14.

Important to note also that npm v3 does not install peer dependencies (and does not error and exit when there is a version conflict, only produces a warning).

**Comment by gregthebusker** [comment]
React 0.14 just became stable.  Would love to see this merged.

**Comment by tajo** [comment]
Yes. I'll review & merge it on Friday or Sat.

**Comment by tajo** [comment]
Thanks @nicolashery!

**Comment by nicolashery** [comment]
:+1:

**Pull request merged**
