### PR TITLE
fix: use cloneElement instead of div.openByClickOn

### PR DESCRIPTION
**Pull request by theaqua**
It's all because box model in CSS.

`div` by default holds 100% width and as you see, my toggle-portal-button actually is not a button, it's a `div`.

image

---
So this PR fixes it by using `React.cloneElement` for extends `this.props.openByClickOn`-element with `onClick` prop and button became a button :)

image

### CODE REVIEW

**Comment by tajo** [comment]
This is great! I've been once trying to solve the exact same thing (but unsuccessfully). :-)

Can you please update this PR, so it's passing Travis CI? Unfortunately, I just completely changed the whole build process (check the readme/contribution or package.json scripts). The repo was also force pushed (history cleaning). Thank you!

**Comment by theaqua** [comment]
Yes, of course, but I don't see Travis log and don't know what exactly I need to fix 😭

image

**Comment by theaqua** [comment]
Hm, can you give me an idea how to fix [this test](https://travis-ci.org/tajo/react-portal/jobs/101756450#L167)?

I don't have experience with React testing, to be honest, and don't know how to use `enzyme`.

The test fails because now `<Portal>` doesn't contain `button`, a button is the top-level element in Portal. We need fix spec probably?

**Comment by theaqua** [comment]
@tajo ?

**Comment by PeteJodo** [comment]
@theaqua you have a couple options. Check out the docs for [enzyme](https://github.com/airbnb/enzyme/blob/master/docs/api/mount.md). You could use the `wrapper.is(selector)` method possibly

**Comment by brianespinosa** [comment]
Nice. This keeps the markup more clean too. Hopefully the PR gets merged soon. Great work, @theaqua .

**Comment by theaqua** [comment]
Hey, @tajo, I changed spec for using `.text` instead of `.contains` (https://github.com/theaqua/react-portal/commit/96044a3ba88bcbc694011f60517ec63844b8923e). Is it acceptable?

**Comment by tajo** [comment]
Looking good. Thanks!

**Pull request merged**
