### PR TITLE
Accept onUpdate callback to notify parent after portal is rerendered

### PR DESCRIPTION
**Pull request by zdenekkostal**

### CODE REVIEW

**Comment by tajo** [comment]
What's the use case? When is this callback needed? Thanks.

**Comment by zdenekkostal** [comment]
We're using the portal for displaying all sorts of modals, dropdowns and bubbles. We need to measure dimensions of portal content to be able to choose best position for aligning to other elements on the page. Because the render happens asynchronously, we're not able to tell when the portal is ready for measuring.

**Comment by tajo** [comment]
Thanks! Merged and released as `v1.5.0`.

**Comment by zdenekkostal** [comment]
That was quick, thanks! :+1:

**Pull request merged**
