### PR TITLE
Add onOpen callback to props

### PR DESCRIPTION
**Pull request by nicolashery**
I needed to position the portal over the element that opens it (kind of like a tooltip or a dropdown). For that I needed access to then opening element's node so I could get its position.

This led me to create an `onOpen` prop that is passed the click event and can return extra child props. It solves my problem, but can also serve as a more generic hook into the portal (mirroring the existing `onClose` prop).

Please see the updated `README` and `examples/` folder. Let me know what you think!

### CODE REVIEW

**Comment by tajo** [comment]
Thanks for your PR. I think your use-case is valid and I'm absolutely fine with adding `onOpen` API. However, the passing (and cloning) of `extraProps` is not very idiomatic. What about some more straightforward solution? You can create a state `{top, left, width}` in the main (parent) component, the `onOpen` callback can update it and then it's possible to simply pass it as a prop of `<AbsolutePosition />`. That seems to be more a "React way".  What do you think?

**Comment by nicolashery** [comment]
Thanks for your feedback! Yes, I was a bit unhappy with the returning of "extra props" from the `onOpen` function. Your suggestion makes it more "React way".

I gave it a shot, but you'll notice that I had to add a callback to `onOpen`'s arguments (its signature is now `onOpen(clickEvent, renderCallback)`). The reason is that without it, the portal didn't get the correct `top, left, width` values the first time you clicked. I think because the portal rendered (opened) before the parent re-rendered with an updated state. The callback ensures the parent render completes before the portal opens.

What do you think? Does this complicate things too much? If you have any other suggestions I'd be happy to hear them. Thanks!

**Comment by tajo** [comment]
Can you please push new (updated) commits?

**Comment by nicolashery** [comment]
I did (used force push to keep git history "clean").

**Comment by tajo** [comment]
I was thinking more about the whole `onOpen` thing. I believe it's not necessary at all. You can simply do this instead:

 `var button3 = <button onClick={your_callback}>Open portal on top of button</button>;`

You always control the opening of portal; thus, there should be no real need for the `onOpen` hook. It's different with `onClose` where it is out of your control if you don't open/close portal through the prop `isOpened`.

**Comment by nicolashery** [comment]
Hum you are right, if we can avoid adding stuff to the API, all the better.

I explored your suggestion (see my latest commits). I still had the problem of the absolute positioning not being set correctly when you opened the portal for the first time, so had to make a few tweaks to `renderPortal` and `openPortal`. See anything wrong with doing that?

**Comment by tajo** [comment]
The current (last) version doesn't work?

**Comment by nicolashery** [comment]
No, just tried out my example on this branch with the `lib/portal.js` from `master`, and the first time you click on the button the portal opens at the bottom of the page (vs. on top of the button). This is because the `top`, `left` state of the parent is set at the same time as `isOpened`, but the new props aren't passed to the portal in `componentWillReceiveProps` (`this.openPortal()` vs `this.openPortal(newProps)` in `lib/portal.js`).

To get it to work with the current version, I would need to do this (in the button's `onClick`):

```javascript
this.setState({
  top: targetRect.top - bodyRect.top,
  left:  targetRect.left - bodyRect.left,
  width: targetRect.width
}, () => this.setState({
  isOpened: true
}));
```

Which feels like a hack. With my fixes, I can simply write this:

```javascript
this.setState({
  isOpened: true,
  top: targetRect.top - bodyRect.top,
  left:  targetRect.left - bodyRect.left,
  width: targetRect.width
});
```

This goes for any other props passed down from the parent's state to the portal. The first time the portal renders, it will get the "previous" version of the parent's state.

Does that make sense?

**Comment by tajo** [comment]
It does. Thanks!

**Comment by silvenon** [comment]
Maybe the docs shouldn't discourage using `isOpened`. Sometimes using it is more elegant (like in this case).

**Pull request merged**
