### PR TITLE
Updated README with information about React Fragments and example

### PR DESCRIPTION
**Pull request by hamczu**

### CODE REVIEW

**Comment by tajo** [comment]
I think we should wait with this until Babel7 (with fragment support) is out since most of people use it to compile JSX.

**Comment by tajo** [comment]
@hamczu That would be good too. Could you also update [code example](https://github.com/tajo/react-portal/blob/master/examples/index.js#L76)?

**Comment by hamczu** [comment]
@tajo done, I replaced <> syntax with React.Fragment - now it's consistent with React's docs

**Comment by tajo** [comment]
@hamczu It still doesn't update the [code example](https://github.com/tajo/react-portal/blob/master/examples/index.js#L76)?

**Comment by hamczu** [comment]
@tajo I'm sorry, I thought you meant the example in the README - updated.

**Comment by tajo** [comment]
Thanks!

**Pull request merged**
