### PR TITLE
Only call `onClose` when Portal is actually closed

### LINKED ISSUE #95: `onClose` called when it should not be called
Consider this implementation

``` js
import React, { Component, PropTypes } from "react";
import Portal from 'react-portal';

export default class Button extends Component {
    state = {
        portalIsOpened: false,
    }

    onClose = () => {
        console.log('on close');
    }

    beforeClose = (node, resetPortalState) => {
        console.log('before close');
    }

    render() {
        return (
            <Portal
                beforeClose={this.beforeClose}
                onClose={this.onClose}
                closeOnEsc
                closeOnOutsideClick
                isOpened={this.state.portalIsOpened}
            >
                <div>
                    <h2>Pseudo Modal</h2>
                    <p>This react component is appended to the document body.</p>
                </div>
            </Portal>
        );
    }
}
```

Element in portal should be closed if user presses ESC key or clicks outside. 
Having above implementation, I decide when to close portal. In order to close portal manually I receive `resetPortalState` callback.

Use Case
- Open portal and press ESC to close it
- Actual Console output

```
"before close"
"on close"
```
- Expected Console output

```
"before close"
```

The issue is `onClose` is triggered even if portal is not actually closed.

`onClose` should be closed only and after `resetPortalState` is invoked and "done".

### PR DESCRIPTION
**Pull request by Andreyco**
Fixes #95

### CODE REVIEW

**Comment by tajo** [comment]
I want to merge this. Could you please add an test checking this behaviour and resolve conflicts? Thanks!

**Comment by mzygmunt** [comment]
Ohh is there any chance to merge this patch?

**Comment by Andreyco** [comment]
Sorry, somehow I missed the comment where about express will to merge...
Will add tests and resolve conflicts asap.

**Comment by mzygmunt** [comment]
Thanks for quick response.

**Comment by likerRr** [comment]
@Andreyco any updates on tests?

**Comment by tajo** [comment]
Hey, please check the new major version (complete rewrite) of react-portal:  https://github.com/tajo/react-portal/issues/157

**It's React v16 only since its uses the new official Portal API**. There is the first beta released and I would like to get your feedback. I don't have bandwidth to maintain v3 which is very different and full of hacks. 

If you feel your PR still applies, please rebase it against the master and re-open it. Sorry for the lack of response in past! Thanks!

**Pull request closed without merging**
