### PR TITLE
moved the openPortal function call 

### PR DESCRIPTION
**Pull request by A11oW**
Moved the openPortal function call from componentWillMount to componentDidMount.
If openPortal call in componentWillMount we have access to DOM elements.
This need for create tooltip. We can connect Parent component with inner Poratal element.

### CODE REVIEW

**Comment by olegakbarov** [comment]
LGTM

**Comment by A11oW** [comment]
Some questions? =)

**Comment by tajo** [comment]
I'll take a look in few days! Sorry.

**Comment by tajo** [comment]
Looks good. Thanks!

**Pull request merged**
