### PR TITLE
add passTrough parameters to closePortal()

### PR DESCRIPTION
**Pull request by robinfehr**
- add pass trough params to the closePortal func
- change file ending for jsx files, change webpack accordingly
- fix tests
- update babel-preset-es2015
- add babel-preset-stage2 (nec. for named parameters and more)
- fixing lint errors

### CODE REVIEW

**Comment by tajo** [comment]
Reasons, examples, tests for `add pass trough params to the closePortal func` ?

```
change file ending for jsx files, change webpack accordingly
```

Why? I'm quite happy with using `.js`.

Also, you should probably split new features and things like `update babel-preset-es2015` into different PRs.

This PR is not acceptable so I'm closing it. But feel free to reopen it with updates and comments.

Thank you!

**Comment by robinfehr** [comment]
hey @tajo - let's quickly discuss it and then I'll reopen them accordingly :)

my reason for the passTrough: 
I'm currently implementing a drag and drop functionality. When for example a list entry gets dragged within the portal not only the portal has to be close but also the dragged entry details need to be passed to the onClose handler. Of course we could add an extra prop with another function but I'd much prefer to have it passed trough.

my reasons for jsx:
jsx is recommended by AirBnb guys (which we currently use) and some editors do not support a correct syntax highlighting without the .jsx file ending

what do you think? :)

**Comment by jdomizio** [comment]
There exist compelling (to me) arguments against the use of a jsx extension as well (https://github.com/facebookincubator/create-react-app/issues/87)

**Comment by robinfehr** [comment]
Yeah fb against airbnb haha id say its a matter of taste in the end - lets leave it :)

**Pull request closed without merging**
