### PR TITLE
Added functionality for portal targets

### PR DESCRIPTION
**Pull request by royteusink**
support for portal targets. A way to place portals in targeted places in the document, rather than always at the bottom.

Fixes issue: https://github.com/tajo/react-portal/issues/99

### CODE REVIEW

**Comment by jvitela** [comment]
Is this functionality planned to be merged? I would also find it very useful.

**Comment by Artsu** [comment]
Also interested about if/when this could be merged.

**Comment by robinfehr** [comment]
👍  would also be very interested.

**Comment by tajo** [comment]
Ok, I want to merge this.

Can you (or somebody else) please update the README, add some tests and resolve conflicts? 

Sorry for not responding sooner.
Thank you!

**Comment by Hypnosphi** [comment]
1. Can you make `props.target` accept a DOM element?
2. Can you make it dynamic, i.e. support changing of target?

**Comment by tajo** [comment]
Done: https://github.com/tajo/react-portal/issues/157

**Pull request closed without merging**
