### PR TITLE
Fix #87: Override isUnmounted in resetPortalState

### LINKED ISSUE #87: Allow resetPortalState to take an argument to override isUnmounted
Would like to allow `resetPortalState` to take an argument to override `isUnmounted` that is defined from the enclosing `closePortal` method.

There could be cases where `beforeClose` executes some async UI behaviors and calls `removeFromDOM` after the Portal has already been unmounted.

One example is when a route changes which can unmount an entire tree of components and `beforeClose` is executing some UI behaviors before it executes `removeFromDOM`.

In those instances it will throw a warning:

```
warning.js:45 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.
```

We could resolve the warning If we allow `resetPortalState` to take an argument to override `isUnmounted`.

I understand this feels like a hacky patch, but it's also non-invasive.

### PR DESCRIPTION
**Pull request by hinok**
# PR for `3.x`

This is fix for https://github.com/tajo/react-portal/issues/87

In the last few days I've encountered this problem in my application. Unfortunately I'm not fully ready to upgrade React to v16 and it seems that react-portal v4 is still in progress 🚀 

If PR will be accepted, may I ask you for pushing it to npm?

### CODE REVIEW

**Comment by tajo** [comment]
I'll accept it if you add a test. Thanks!

**Comment by hinok** [comment]
@tajo tests added.

**Comment by tajo** [comment]
thanks, released as `v3.2.0`

**Comment by hinok** [comment]
Thank you very much!

**Pull request merged**
